Pages/AddExpenditure.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using RazorLoginRegister.Data;
using RazorLoginRegister.Models;
using System.ComponentModel.DataAnnotations;

namespace RazorLoginRegister.Pages
{
    public class AddExpenditureModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public AddExpenditureModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ExpenditureInputModel Input { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var expenditure = new Expenditure
            {
                Amount = Input.Amount,
                Description = Input.Description,
                Date = Input.Date,
                UserId = userId.Value
            };

            _context.Expenditures.Add(expenditure);
            _context.SaveChanges();

            return RedirectToPage("/ExpenditureDetails");
        }

        public class ExpenditureInputModel
        {
            [Required]
            public decimal Amount { get; set; }

            [Required]
            public string Description { get; set; }

            [Required]
            [DataType(DataType.Date)]
            public DateTime Date { get; set; }
        }
    }
}

Pages/AddIncome.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using RazorLoginRegister.Data;
using RazorLoginRegister.Models;
using System.ComponentModel.DataAnnotations;

namespace RazorLoginRegister.Pages
{
    public class AddIncomeModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public AddIncomeModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public IncomeInputModel Input { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var income = new Income
            {
                Amount = Input.Amount,
                Description = Input.Description,
                Date = Input.Date,
                UserId = userId.Value
            };

            _context.Incomes.Add(income);
            _context.SaveChanges();

            return RedirectToPage("/IncomeDetails");
        }

        public class IncomeInputModel
        {
            [Required]
            public decimal Amount { get; set; }

            [Required]
            public string Description { get; set; }

            [Required]
            [DataType(DataType.Date)]
            public DateTime Date { get; set; }
        }
    }
}

Pages/AddTransaction.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using RazorLoginRegister.Data;
using RazorLoginRegister.Models;
using System.ComponentModel.DataAnnotations;

namespace RazorLoginRegister.Pages
{
    public class AddTransactionModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public AddTransactionModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public TransactionInputModel Input { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Input.Type == "Income")
            {
                var income = new Income
                {
                    Amount = Input.Amount,
                    Description = Input.Description,
                    UserId = userId.Value
                };

                _context.Incomes.Add(income);
            }
            else
            {
                var expenditure = new Expenditure
                {
                    Amount = Input.Amount,
                    Description = Input.Description,
                    UserId = userId.Value
                };

                _context.Expenditures.Add(expenditure);
            }

            _context.SaveChanges();

            return RedirectToPage("/MoneyFlow");
        }

        public class TransactionInputModel
        {
            [Required]
            public decimal Amount { get; set; }

            [Required]
            public string Description { get; set; }

            [Required]
            public string Type { get; set; }
        }
    }
}

Pages/EditExpenditure.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorLoginRegister.Data;
using RazorLoginRegister.Models;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace RazorLoginRegister.Pages
{
    public class EditExpenditureModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditExpenditureModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ExpenditureInputModel Input { get; set; }
        public int ExpenditureId { get; set; }

        public IActionResult OnGet(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            var expenditure = _context.Expenditures.FirstOrDefault(e => e.Id == id && e.UserId == userId.Value);
            if (expenditure == null)
            {
                return NotFound();
            }

            ExpenditureId = expenditure.Id;
            Input = new ExpenditureInputModel
            {
                Amount = expenditure.Amount,
                Description = expenditure.Description,
                Date = expenditure.Date
            };

            return Page();
        }

        public IActionResult OnPost(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var expenditure = _context.Expenditures.FirstOrDefault(e => e.Id == id && e.UserId == userId.Value);
            if (expenditure == null)
            {
                return NotFound();
            }

            expenditure.Amount = Input.Amount;
            expenditure.Description = Input.Description;
            expenditure.Date = Input.Date;

            _context.SaveChanges();

            return RedirectToPage("/ExpenditureDetails");
        }

        public IActionResult OnPostDelete(int id)
        {
            var expenditure = _context.Expenditures.Find(id);
            if (expenditure != null)
            {
                _context.Expenditures.Remove(expenditure);
                _context.SaveChanges();
            }
            return RedirectToPage("/ExpenditureDetails");
        }

        public class ExpenditureInputModel
        {
            [Required]
            public decimal Amount { get; set; }

            [Required]
            public string Description { get; set; }

            [Required]
            [DataType(DataType.Date)]
            public DateTime Date { get; set; }
        }
    }
}

Pages/EditIncome.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorLoginRegister.Data;
using RazorLoginRegister.Models;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace RazorLoginRegister.Pages
{
    public class EditIncomeModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditIncomeModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public IncomeInputModel Input { get; set; }
        public int IncomeId { get; set; }

        public IActionResult OnGet(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            var income = _context.Incomes.FirstOrDefault(i => i.Id == id && i.UserId == userId.Value);
            if (income == null)
            {
                return NotFound();
            }

            IncomeId = income.Id;
            Input = new IncomeInputModel
            {
                Amount = income.Amount,
                Description = income.Description,
                Date = income.Date
            };

            return Page();
        }

        public IActionResult OnPost(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var income = _context.Incomes.FirstOrDefault(i => i.Id == id && i.UserId == userId.Value);
            if (income == null)
            {
                return NotFound();
            }

            income.Amount = Input.Amount;
            income.Description = Input.Description;
            income.Date = Input.Date;

            _context.SaveChanges();

            return RedirectToPage("/IncomeDetails");
        }

        public IActionResult OnPostDelete(int id)
        {
            var income = _context.Incomes.Find(id);
            if (income != null)
            {
                _context.Incomes.Remove(income);
                _context.SaveChanges();
            }
            return RedirectToPage("/IncomeDetails");
        }

        public class IncomeInputModel
        {
            [Required]
            public decimal Amount { get; set; }

            [Required]
            public string Description { get; set; }

            [Required]
            [DataType(DataType.Date)]
            public DateTime Date { get; set; }
        }
    }
}

Pages/ExpenditureDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using RazorLoginRegister.Data;
using RazorLoginRegister.Models;
using System.Collections.Generic;
using System.Linq;

namespace RazorLoginRegister.Pages
{
    public class ExpenditureDetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public ExpenditureDetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public List<Expenditure> Expenditures { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public decimal TotalExpenditure { get; set; }

        public IActionResult OnGet(int currentPage = 1)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            const int pageSize = 5;
            var expendituresQuery = _context.Expenditures.Where(e => e.UserId == userId.Value);
            var totalExpenditures = expendituresQuery.Count();

            TotalPages = (int)System.Math.Ceiling(totalExpenditures / (double)pageSize);
            CurrentPage = currentPage;
            TotalExpenditure = expendituresQuery.AsEnumerable().Sum(e => e.Amount);

            Expenditures = expendituresQuery
                .OrderBy(e => e.Date)
                .Skip((CurrentPage - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            return Page();
        }
    }
}

Pages/IncomeDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using RazorLoginRegister.Data;
using RazorLoginRegister.Models;
using System.Collections.Generic;
using System.Linq;

namespace RazorLoginRegister.Pages
{
    public class IncomeDetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public IncomeDetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public List<Income> Incomes { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public decimal TotalIncome { get; set; }

        public IActionResult OnGet(int currentPage = 1)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            const int pageSize = 5;
            var incomesQuery = _context.Incomes.Where(i => i.UserId == userId.Value);
            var totalIncomes = incomesQuery.Count();

            TotalPages = (int)System.Math.Ceiling(totalIncomes / (double)pageSize);
            CurrentPage = currentPage;
            TotalIncome = incomesQuery.AsEnumerable().Sum(i => i.Amount);

            Incomes = incomesQuery
                .OrderBy(i => i.Date)
                .Skip((CurrentPage - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            return Page();
        }
    }
}

Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using RazorLoginRegister.Data;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace RazorLoginRegister.Pages
{
    public class LoginModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public LoginModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public LoginInputModel Input { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = _context.Users.SingleOrDefault(u => u.Username == Input.Username && u.Password == Input.Password);
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return Page();
            }

            HttpContext.Session.SetInt32("UserId", user.Id);

            return RedirectToPage("/MoneyFlow");
        }

        public class LoginInputModel
        {
            [Required]
            public string Username { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }
        }
    }
}

Pages/MoneyFlow.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using RazorLoginRegister.Data;
using RazorLoginRegister.Models;
using System.Linq;

namespace RazorLoginRegister.Pages
{
    public class MoneyFlowModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public MoneyFlowModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public decimal TotalIncome { get; set; }
        public decimal TotalExpenditure { get; set; }

        public IActionResult OnGet()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("/Login");
            }

            TotalIncome = _context.Incomes
                .Where(i => i.UserId == userId.Value)
                .AsEnumerable() 
                .Sum(i => i.Amount);

            TotalExpenditure = _context.Expenditures
                .Where(e => e.UserId == userId.Value)
                .AsEnumerable()
                .Sum(e => e.Amount);

            return Page();
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Remove("UserId");
            return RedirectToPage("/Login");
        }
    }
}

Pages/AddExpenditure.cshtml
@page
@model RazorLoginRegister.Pages.AddExpenditureModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Add Expenditure";
}

<h2>Add Expenditure</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Input.Amount"></label>
        <input asp-for="Input.Amount" class="form-control" />
        <span asp-validation-for="Input.Amount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Description"></label>
        <input asp-for="Input.Description" class="form-control" />
        <span asp-validation-for="Input.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Date"></label>
        <input asp-for="Input.Date" class="form-control" type="date" />
        <span asp-validation-for="Input.Date" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<form method="get" action="/ExpenditureDetails">
    <button type="submit" class="btn btn-secondary">Back to Expenditure Details</button>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Pages/AddIncome.cshtml
@page
@model RazorLoginRegister.Pages.AddIncomeModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Add Income";
}

<h2>Add Income</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Input.Amount"></label>
        <input asp-for="Input.Amount" class="form-control" />
        <span asp-validation-for="Input.Amount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Description"></label>
        <input asp-for="Input.Description" class="form-control" />
        <span asp-validation-for="Input.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Date"></label>
        <input asp-for="Input.Date" class="form-control" type="date" />
        <span asp-validation-for="Input.Date" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<form method="get" action="/IncomeDetails">
    <button type="submit" class="btn btn-secondary">Back to Income Details</button>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Pages/AddTransaction.cshtml
@page
@model RazorLoginRegister.Pages.AddTransactionModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Add Transaction";
}

<h2>Add Transaction</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Input.Amount"></label>
        <input asp-for="Input.Amount" class="form-control" />
        <span asp-validation-for="Input.Amount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Description"></label>
        <input asp-for="Input.Description" class="form-control" />
        <span asp-validation-for="Input.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Type"></label>
        <select asp-for="Input.Type" class="form-control">
            <option value="Income">Income</option>
            <option value="Expenditure">Expenditure</option>
        </select>
        <span asp-validation-for="Input.Type" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-page="/MoneyFlow" class="btn btn-secondary">Back</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Pages/EditExpenditure.cshtml
@page "{id:int}"
@model RazorLoginRegister.Pages.EditExpenditureModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Edit Expenditure";
}

<h2>Edit Expenditure</h2>

<form method="get" action="/ExpenditureDetails">
    <button type="submit" class="btn btn-secondary">Back to Expenditure Details</button>
</form>

<form method="post">
    <div class="form-group">
        <label asp-for="Input.Amount"></label>
        <input asp-for="Input.Amount" class="form-control" />
        <span asp-validation-for="Input.Amount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Description"></label>
        <input asp-for="Input.Description" class="form-control" />
        <span asp-validation-for="Input.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Date"></label>
        <input asp-for="Input.Date" class="form-control" type="date" />
        <span asp-validation-for="Input.Date" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<form method="post" asp-page-handler="Delete" asp-route-id="@Model.ExpenditureId">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Pages/EditIncome.cshtml
@page "{id:int}"
@model RazorLoginRegister.Pages.EditIncomeModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Edit Income";
}

<h2>Edit Income</h2>

<form method="get" action="/IncomeDetails">
    <button type="submit" class="btn btn-secondary">Back to Income Details</button>
</form>

<form method="post">
    <div class="form-group">
        <label asp-for="Input.Amount"></label>
        <input asp-for="Input.Amount" class="form-control" />
        <span asp-validation-for="Input.Amount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Description"></label>
        <input asp-for="Input.Description" class="form-control" />
        <span asp-validation-for="Input.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Date"></label>
        <input asp-for="Input.Date" class="form-control" type="date" />
        <span asp-validation-for="Input.Date" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<form method="post" asp-page-handler="Delete" asp-route-id="@Model.IncomeId">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Pages/ExpenditureDetails.cshtml
@page "{currentPage:int?}"
@model RazorLoginRegister.Pages.ExpenditureDetailsModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Expenditure Details";
}

<h2>Expenditure Details</h2>

<div class="text-center">
    <form method="get" asp-page="AddExpenditure">
        <button type="submit" class="btn btn-primary">Add Expenditure</button>
    </form>
    <form method="get" action="/MoneyFlow">
        <button type="submit" class="btn btn-secondary">Back to Money Flow</button>
    </form>
</div>


<h3 class="text-center">Total Expenditure: $@Model.TotalExpenditure</h3>

<div class="table-container">
    <table class="table">
        <thead>
            <tr>
                <th>Amount</th>
                <th>Description</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var expenditure in Model.Expenditures)
            {
                <tr>
                    <td>$@expenditure.Amount</td>
                    <td>@expenditure.Description</td>
                    <td>@expenditure.Date.ToShortDateString()</td>
                    <td>
                        <form method="get" asp-page="EditExpenditure" asp-route-id="@expenditure.Id" style="display:inline;">
                            <button type="submit" class="btn btn-warning">Edit</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<nav aria-label="Page navigation">
    <ul class="pagination">
        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                <a class="page-link" asp-page="./ExpenditureDetails" asp-route-currentPage="@i">@i</a>
            </li>
        }
    </ul>
</nav>

Pages/IncomeDetails.cshtml
@page "{currentPage:int?}"
@model RazorLoginRegister.Pages.IncomeDetailsModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Income Details";
}

<h2>Income Details</h2>

<div class="text-center">
    <form method="get" asp-page="AddIncome">
        <button type="submit" class="btn btn-primary">Add Income</button>
    </form>
    <form method="get" action="/MoneyFlow">
        <button type="submit" class="btn btn-secondary">Back to Money Flow</button>
    </form>
</div>

<h3 class="text-center">Total Income: $@Model.TotalIncome</h3>

<div class="table-container">
    <table class="table">
        <thead>
            <tr>
                <th>Amount</th>
                <th>Description</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var income in Model.Incomes)
            {
                <tr>
                    <td>$@income.Amount</td>
                    <td>@income.Description</td>
                    <td>@income.Date.ToShortDateString()</td>
                    <td>
                        <form method="get" asp-page="EditIncome" asp-route-id="@income.Id" style="display:inline;">
                            <button type="submit" class="btn btn-warning">Edit</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<nav aria-label="Page navigation">
    <ul class="pagination">
        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                <a class="page-link" asp-page="./IncomeDetails" asp-route-currentPage="@i">@i</a>
            </li>
        }
    </ul>
</nav>

Pages/Login.cshtml
@page
@model RazorLoginRegister.Pages.LoginModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Login";
}

<h2>Login</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Input.Username"></label>
        <input asp-for="Input.Username" class="form-control" />
        <span asp-validation-for="Input.Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Password"></label>
        <input asp-for="Input.Password" type="password" class="form-control" />
        <span asp-validation-for="Input.Password" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

<form method="get" action="/Register">
    <button type="submit" class="btn btn-secondary">Register</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Pages/MoneyFlow.cshtml
@page
@model RazorLoginRegister.Pages.MoneyFlowModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Money Flow";
}

<h2>Money Flow</h2>

<div class="summary">
    <div class="summary-item">
        <h3>Total Income: @Model.TotalIncome</h3>
        <form method="get" asp-page="IncomeDetails">
            <button type="submit" class="btn btn-primary">View Income Details</button>
        </form>
    </div>
    <div class="summary-item">
        <h3>Total Expenditure: @Model.TotalExpenditure</h3>
        <form method="get" asp-page="ExpenditureDetails">
            <button type="submit" class="btn btn-primary">View Expenditure Details</button>
        </form>
    </div>
</div>

<form method="post" asp-page-handler="Logout">
    <button type="submit" class="btn btn-primary">Logout</button>
</form>

Pages/Register.cshtml
@page
@model RazorLoginRegister.Pages.RegisterModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Register";
}

<h2>Register</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Input.Username"></label>
        <input asp-for="Input.Username" class="form-control" />
        <span asp-validation-for="Input.Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Email"></label>
        <input asp-for="Input.Email" class="form-control" />
        <span asp-validation-for="Input.Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.Password"></label>
        <input asp-for="Input.Password" type="password" class="form-control" />
        <span asp-validation-for="Input.Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Input.ConfirmPassword"></label>
        <input asp-for="Input.ConfirmPassword" type="password" class="form-control" />
        <span asp-validation-for="Input.ConfirmPassword" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
</form>

<form method="get" action="/Login">
    <button type="submit" class="btn btn-secondary">Back to Login</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}